package main

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	datasourceschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

type RunModel struct {
	Command      []types.String `tfsdk:"command"`
	Environment  types.Map      `tfsdk:"environment"`
	WorkingDir   types.String   `tfsdk:"working_dir"`
	Outputs      []types.String `tfsdk:"outputs"`
	OutputHashes types.List     `tfsdk:"output_hashes"`
}

type Run struct {
}

func (Run) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_run"
}

func (Run) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasourceschema.Schema{
		MarkdownDescription: "Run a command",
		Attributes: map[string]datasourceschema.Attribute{
			"command": datasourceschema.ListAttribute{
				MarkdownDescription: "Command to run; first element is executable, remaining elements are arguments",
				ElementType:         types.StringType,
				Required:            true,
			},
			"environment": datasourceschema.MapAttribute{
				MarkdownDescription: "Environment variables; inherits terraform's environment",
				ElementType:         types.StringType,
				Optional:            true,
			},
			"working_dir": datasourceschema.StringAttribute{
				MarkdownDescription: "Working directory in which to run command; defaults to current directory",
				Optional:            true,
			},
			"outputs": datasourceschema.ListAttribute{
				MarkdownDescription: "Paths to files generated by the command, relative to working directory; the hashes of these are placed in `output_hashes` after execution",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"output_hashes": datasourceschema.ListAttribute{
				MarkdownDescription: "The hashes of the output files, updated after execution",
				Computed:            true,
				ElementType:         types.StringType,
			},
		},
	}
}
func (r Run) run(state *RunModel, diagnostics *diag.Diagnostics) {
	cmd0 := []string{}
	for _, c := range state.Command {
		cmd0 = append(cmd0, c.ValueString())
	}
	cmd := exec.Command(cmd0[0], cmd0[1:]...)
	env := map[string]string{}
	for _, e := range os.Environ() {
		parts := strings.SplitN(e, "=", 2)
		env[parts[0]] = parts[1]
	}
	for k, v := range state.Environment.Elements() {
		v1 := v.(basetypes.StringValue)
		env[k] = v1.ValueString()
	}
	env1 := []string{}
	for k, v := range env {
		env1 = append(env1, fmt.Sprintf("%s=%s", k, v))
	}
	cmd.Env = env1
	cmd.Dir = state.WorkingDir.ValueString()
	out, err := cmd.CombinedOutput()
	if err != nil {
		diagnostics.AddError("Run failed", string(out))
		return
	}
}

func (r Run) updateHashes(state *RunModel, diagnostics *diag.Diagnostics) {
	out := []attr.Value{}
	for _, o := range state.Outputs {
		var p string
		if filepath.IsAbs(o.ValueString()) {
			// Work around filepath incorrectly joining abs to abs paths
			p = o.ValueString()
		} else {
			var err error
			p, err = filepath.Abs(filepath.Join(state.WorkingDir.ValueString(), o.ValueString()))
			if err != nil {
				panic(err)
			}
		}
		digest := sha256.New()
		f, err := os.Open(p)
		if err != nil {
			diagnostics.AddError("Failed to open output file "+p, err.Error())
			goto Err
		}
		defer func() {
			err := f.Close()
			if err != nil {
				diagnostics.AddWarning("Failed to close output file "+p, err.Error())
			}
		}()
		_, err = io.Copy(digest, f)
		if err != nil {
			diagnostics.AddError("Failed to hash output file "+p, err.Error())
			goto Err
		}
		out = append(out, types.StringValue(hex.EncodeToString(digest.Sum([]byte{}))))
		continue
	Err:
		out = append(out, types.StringValue("error"))
	}
	var diags diag.Diagnostics
	state.OutputHashes, diags = types.ListValue(types.StringType, out)
	diagnostics.Append(diags...)
	if diagnostics.HasError() {
		return
	}
}

func (r Run) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state RunModel
	diags := req.Config.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	r.run(&state, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.updateHashes(&state, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}
